server:
  port: 8003

#redis配置
spring:
  redis:
    database: 0
    host: 120.25.149.156
    port: 6379
    password:

#设置域名，在java代码中提取
website:
  domain-name: softnews.com

#dev环境开启mybatis日志
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
