server:
  port: 8005

spring:
  redis:
    database: 0
    host: 120.25.149.156
    port: 6379
    password:

#在dev环境开启mybatis的日志打印
mybatis:
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

    website:
      domain-name: www.sn.com